### ISSUE TITLE
Create tests using Base.Test

### ISSUE THREAD

**Issue by abelsiqueira** [RenanOD/NumInt.jl#14]
See [this](http://julia.readthedocs.org/en/latest/stdlib/test/)
Basically, test that the numerical integrations are returning the expected values using `@test` and other Base.Test macros

``` julia
@test abs(exact - approx) < 1e-6
```

Machine's precision is `eps(Float64)`.

**Comment by RenanOD** [comment]
The new tests are using Base.Test and passing on travis.
