### ISSUE TITLE
Remover problemas de deprecamento

### ISSUE THREAD

**Issue by abelsiqueira** [RenanOD/NumInt.jl#15]
Usando a versão nightly (0.4) existem várias mensagens de coisas deprecadas.
Essencialmente:
- Entre uma função e o parênteses dela não pode ter espaço (`include (` muda para `include(`)
- Usar `for k = [1:10]` é errado, não precisa dos colchetes. Mude para `for k = 1:10`.

**Comment by RenanOD** [comment]
solved, there are no more warnings on the nightly test
