### ISSUE TITLE
Retornar aproximação obtida quando subintervalos excedem no SRA

### ISSUE THREAD

**Issue by abelsiqueira** [RenanOD/NumInt.jl#3]
No SRA.jl, se os subintervalos excedem o limite dado, atualmente o código retorna 0.
Conserte para que retorne a melhor solução obtida, até o momento.

**Comment by RenanOD** [comment]
Corrigido. Além da melhor aproximação, também é retornada uma mensagem informando que o limite de subintervalos foi excedido.
